sudo: false
language: go

go:
  - 1.9.x
  - 1.8.x
  - 1.7.x
  - master

repo_token: q3K2f9nSxazHhcN34eeCSeufIjY4cy6Cm

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
  - go tool vet .
  - ls -la
  - go test ./pipedrive -api -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN